---
name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pako-23/action-linters@v0
        env:
          ACTIONLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT: true
          MARKDOWNLINT: true
          YAMLLINT: true
